### ISSUE TITLE
Release: mizani-0.9.2

### ISSUE THREAD

**Issue by has2k1** [has2k1/mizani#31]
- [x] Run tests and coverage locally

  <details>

  ```sh
  git switch main
  git pull origin/main
  make test
  make coverage
  ```
  - [x] The tests pass
  - [x] The coverage is acceptable

  </details>

- [x] The latest [online documentation](https://mizani.readthedocs.io/latest/) builds, be sure to browse

- [x] Create a release branch

  <details>

  ```sh
  git switch -c release-v0.9.2
  ```

  </details>

- [x] Tag a pre-release version. These are automatically deployed on `testpypi`

  <details>

  ```sh
  git tag -as v0.9.2a1 -m "Version 0.9.2a1"  # e.g. 0.9.2a1, 0.9.2b1, 0.9.2rc1
  git push -u origin release-v0.9.2
  ```
  - [x] GHA [release job](https://github.com/has2k1/mizani/actions/workflows/release.yml) passes
  - [x] Mizani test release is on [TestPyPi](https://test.pypi.org/project/mizani)

  </details>

- [x] Update changelog

  <details>

  ```sh
  nvim doc/changelog.rst
  git commit -am "Update changelog for release"
  git push
  ```
  - [x] Update / confirm the version to be released
  - [x] Add a release date
  - [x] The [GHA tests](https://github.com/has2k1/mizani/actions/workflows/testing.yml) pass

  </details>

- [x] Tag final version and release

  <details>

  ```sh
  git tag -as v0.9.2 -m "Version 0.9.2"
  git push
  ```

  - [x] The [GHA Release](https://github.com/has2k1/mizani/actions/workflows/release.yml) job passes
  - [x] [PyPi](https://pypi.org/project/mizani) shows the new release

  </details>

- [x] Update `main` branch

  <details>

  ```sh
  git switch main
  git merge --ff-only release-v0.9.2
  git push
  ```

  - [x] The [GHA Release](https://github.com/has2k1/mizani/actions/workflows/release.yml) job passes
  - [x] [PyPi](https://pypi.org/project/mizani) shows the new release

  </details>

- [x] Create conda release

  <details>

  - [x] Copy _SHA256 hash_. Click view hashes, for the [Source Distribution](https://pypi.org/project/mizani/0.9.2/#files) (`.tar.gz`).

  - [x] Update [mizani-feedsock](https://github.com/conda-forge/mizani-feedstock)

    ```sh
    cd ../mizani-feestock
    git switch main
    git pull upstream main
    git switch -c v0.9.2
    nvim recipe/meta.yml
    git commit -am  "Version 0.9.2"
    git push -u origin v0.9.2
    ```
  - [x] Create a [PR](https://github.com/conda-forge/mizani-feedstock/pulls)
  - [ ] Complete PR (follow the steps and merge)

  </details>

- [x] Add [zenodo badge](https://zenodo.org/account/settings/github/repository/has2k1/mizani) to the changelog.
